-- AlterTable
ALTER TABLE `notificationpreferences` MODIFY `type` ENUM('SYSTEM', 'PROJECT_ASSIGNED', 'TASK_ASSIGNED', 'TASK_UPDATED', 'TASK_COMMENT', 'TASK_BLOCKED', 'MILESTONE_DUE', 'SPRINT_UPDATED', 'DAILY_REPORT', 'CHAT_MESSAGE') NOT NULL;

-- AlterTable
ALTER TABLE `notificationtemplates` MODIFY `type` ENUM('SYSTEM', 'PROJECT_ASSIGNED', 'TASK_ASSIGNED', 'TASK_UPDATED', 'TASK_COMMENT', 'TASK_BLOCKED', 'MILESTONE_DUE', 'SPRINT_UPDATED', 'DAILY_REPORT', 'CHAT_MESSAGE') NOT NULL;

-- AlterTable
ALTER TABLE `usernotifications` MODIFY `type` ENUM('SYSTEM', 'PROJECT_ASSIGNED', 'TASK_ASSIGNED', 'TASK_UPDATED', 'TASK_COMMENT', 'TASK_BLOCKED', 'MILESTONE_DUE', 'SPRINT_UPDATED', 'DAILY_REPORT', 'CHAT_MESSAGE') NOT NULL;
